### ISSUE TITLE
Libgcrypt warning: missing initialization - please fix the application

### ISSUE THREAD

**Issue by roughnecks** [jgeboski/bitlbee-steam#101]
Hi there, I just compiled and installed bitlbee-steam and it's working fine but I noticed this warning in my syslog.

Nov 16 20:35:25 nadir bitlbee[20124]: Stopping BitlBee IRC/IM gateway: bitlbee.
Nov 16 20:35:25 nadir bitlbee[20127]: Starting BitlBee IRC/IM gateway: bitlbee.
Nov 16 20:37:33 nadir bitlbee[20141]: Libgcrypt warning: missing initialization - please fix the application

I'm running Debian Jessie and bitlbee packages from upstream. Thanks

**Comment by jgeboski** [comment]
Resolved as of ccd6e8c.
