### ISSUE TITLE
Steam's chat window pops-up

### ISSUE THREAD

**Issue by roughnecks** [jgeboski/bitlbee-steam#102]
Sorry for the dumb question.. I use bitlbee on a Linux device and I am logged on Steam with my main rig at the same time (even though chat is set to offline).
Every time I send a message via bitlbee, Steam's chat window opens and I can read that very same message; on the contrary, when I receive a message on bitlbee there's no counterpart on Steam.. so I was wondering if I can avoid the Steam chat window to be opened at all in Windows.

Thanks

**Comment by jgeboski** [comment]
To my knowledge this is not possible, unfortunately.
