### ISSUE TITLE
"nickname" has left &bitlbee () as soon as they start playing

### ISSUE THREAD

**Issue by roughnecks** [jgeboski/bitlbee-steam#103]
Is this the correct behavior or just a bug to be fixed?

Thanks

**Comment by dequis** [comment]
Check `channel &bitlbee set show_users`

You should have `special%` in there, the whole thing would be something like `online+,special%,away`

**Comment by roughnecks** [comment]
Thanks, better now (I only had "online,away"); I see all my online/playing friends now, however their status is not consistent - I do not see any special%, some people are shown online+ while they are away and so on.

**Comment by roughnecks** [comment]
Thanks, looks like it's fixed now.
