### ISSUE TITLE
Error when building.

### ISSUE THREAD

**Issue by chadaracine** [jgeboski/bitlbee-steam#104]
./autogen.sh:

    mkdir: cannot create directory ‘m4’: Permission denied
    autoreconf: Entering directory `.'
    autoreconf: configure.ac: not using Gettext
    autoreconf: running: aclocal --force -Im4
    aclocal: warning: couldn't open directory 'm4': No such file or directory
    configure.ac:84: warning: macro 'AM_PATH_LIBGCRYPT' not found in library
    autom4te: cannot create autom4te.cache: No such file or directory
    aclocal: error: echo failed with exit status: 1
    autoreconf: aclocal failed with exit status: 1

I've been looking around for a fix for this, but can't seem to find one anywhere. I've installed bitlbee-facebook with no problem. Ubuntu 14.04.3.

**Comment by dequis** [comment]
Install libgcrypt20-dev

**Comment by chadaracine** [comment]
Yup. Don't know why I had such a hard time with that.
