### ISSUE TITLE
./autogen.sh --enable-debug doesn't seem to work (configure script problem?)

### ISSUE THREAD

**Issue by Fyren** [jgeboski/bitlbee-steam#106]
If I run ```./autogen.sh --enable-debug``` and then make bitlbee-steam, it doesn't seem like ```DEBUG_STEAM``` is actually getting set.  If I run ```nm -C steam.so``` and then grep the output for "debug", the debug symbols aren't there.  If I run ```CFLAGS="-DDEBUG_STEAM" ./configure``` instead, it does work.

**Comment by jgeboski** [comment]
Works for me. Try cleaning out your source tree, and try again?

```
git reset --hard
git clean -dfx
```

**Comment by Fyren** [comment]
Yeah, I dunno what happened here.  Probably my fault.
