### ISSUE TITLE
recent changes may have broken email tokens

### ISSUE THREAD

**Issue by shivalwolf** [jgeboski/bitlbee-steam#109]
I am not sure if this is the best way to report this.

I think the latest updates to support steam guard with the mobile authenticator may have broken the older email verification.

When in email mode I can't authenticate to the steam account the client gets stuck in a loop asking for a captcha code and an authcode then asks for a captcha over and over until steam locks out the connecting IP.

I then switched over to mobile authenticator and it connected and authenticated 1st time without ever asking for a captcha.

**Comment by jgeboski** [comment]
This has been resolved as of 05c7503.
