### ISSUE TITLE
Bogus tabs & spaces appended to outgoing chat messages

### ISSUE THREAD

**Issue by rathsky** [jgeboski/bitlbee-steam#114]
Since a while random tabs are appended to my outgoing messages. While I don't see them in the IRC window/log, sometimes they pop up in the log of my Steam client. Eg, these to a eight word message:

> 	  				 	 	 	    		  	   		  		[ends here]

Dunno if this is a bitlbee (at g242f280) or plugin thing.

**Comment by jgeboski** [comment]
I leaning towards this being an issue with your client/bouncer.

**Comment by dequis** [comment]
It's the opportunistic OTR whitespace marker, either added by the bitlbee otr plugin or by an otr plugin in your client. It's used to (somewhat) silently tell the other person that you support OTR.

**Comment by rathsky** [comment]
Gotta be it, goes along with the recent changes too.

I see now that the bitlbee log has "otr: [account] ready" for all including steam, even though there's nothing regarding it in bitlbee.conf (nor in my weechat configs).

**Comment by jgeboski** [comment]
Good thinking, @dequis! This is a result of ab91711. You could always do: `set otr_policy manual`.

**Comment by rathsky** [comment]
Guess I'll close this then.

Might be considered to make manual the default for steam though, seeing most of us (probably) chat with ordinary steam client users for who the whitespaces only cause confusion (as it did for me).
