### ISSUE TITLE
Is it possible to join a Steam Group chat?

### ISSUE THREAD

**Issue by roughnecks** [jgeboski/bitlbee-steam#115]
If it's not, do you have any plans on adding that feature?

Thanks.

**Comment by jgeboski** [comment]
As soon as Steam supports group chats via the Mobile or Web APIs, then this plugin will support such functionality.

**Comment by roughnecks** [comment]
Sorry to bother you again.

I'm not sure how ASF does it, but it's already able to connect bot instances to Steam Groups Chat... Aren't they using Mobile/Web APIs too?

https://github.com/JustArchi/ArchiSteamFarm

> SteamMasterClanID - ulong type with default value of 0. This property is similar to SteamMasterID, but it defines the steamID of the steam group that bot should automatically join, including group chat. You can check steamID of your group by navigating to it's page, then adding /memberslistxml/?xml=1 to the end of the link, so the link will look like this. Then you can get steamID of your group from the result, it's in <groupID64> tag. In above example it would be 103582791440160998. If you don't have any "farm group" for your bots, you should keep it at default.

**Comment by jgeboski** [comment]
According to the ASF README, it uses SteamKit, which is a reverse engineered .NET library for the actual Steam protocol.

**Comment by roughnecks** [comment]
I see. Was hoping for better news, but thanks anyway.

**Comment by Andrewskiz** [comment]
@jgeboski Is it possible that bitlbee-steam could support group chats now that they're supported via the web api? That would be amazing
