### ISSUE TITLE
autogen.sh fails to complete, claiming "excess arguments to builtin 'm4_define' [...]"

### ISSUE THREAD

**Issue by ghost** [jgeboski/bitlbee-steam#54]
My server is on a fresh installation of Debian Wheezy 32-bit. I first installed dh-autoreconf and used "git clone" to clone the repository. Then, I execute ./autogen.sh. It does not work.

```
root@kironide:~/bitlbee-steam# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
/usr/bin/m4:configure.ac:77: Warning: excess arguments to builtin `m4_define' ignored
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
root@kironide:~/bitlbee-steam#
```

**Comment by devcline** [comment]
Hello, Freebsd Here, installed with pkg install bitlbee
bitlbee-stema is placed in /root

   configure: WARNING:
   ***
   *** The config script /usr/local/bin/libgcrypt-config was
   *** built for x86_64-portbld-freebsd9.1 and thus may not match the
   *** used host amd64-unknown-freebsd9.1.
   *** You may want to use the configure option --with-libgcrypt-prefix
   *** to specify a matching config script.
   ***
   checking for pkg-config... /usr/local/bin/pkg-config
   checking pkg-config is at least version 0.9.0... yes
   checking for GLIB... yes
   checking for BITLBEE... no
   configure: error: Package requirements (bitlbee  >= 3.4) were not met:

   Package bitlbee was not found in the pkg-config search path.
   Perhaps you should add the directory containing `bitlbee.pc'
   to the PKG_CONFIG_PATH environment variable
   Package 'bitlbee', required by 'world', not found

   Consider adjusting the PKG_CONFIG_PATH environment variable if you
   installed software in a non-standard prefix.

   Alternatively, you may set the environment variables BITLBEE_CFLAGS
   and BITLBEE_LIBS to avoid the need to call pkg-config.
   See the pkg-config man page for more details.

**Comment by jgeboski** [comment]
@devcline This issue is over a year old.  Please open a new issue next time.

As for your error, it is pretty self explanatory: `Package requirements (bitlbee >= 3.4) were not me`.  Install or upgrade bitlbee to at least version 3.4 with the development files.  If you are building by hand, `make install-dev`

**Comment by devcline** [comment]
Thanks! im sorry, i will.  From packages

pkg search bitlbee
bitlbee-3.4.1_2
