### ISSUE TITLE
Implement support for two-factor authentication

### ISSUE THREAD

**Issue by jgeboski** [jgeboski/bitlbee-steam#75]
Valve is currently in the process of supporting two-factor authentication, aside from their current SteamGuard implementation.  It can only be assumed this will be some sort of OTP implementation.  While the changes can be seen within the Steam API, it has yet to be implemented for any users.

In order for this plugin to remain compatible with all security features offered by Steam, it should adopt support for two-factor authentication.

**Comment by vodik** [comment]
Yeah, currently I am not able to authenticate this plugin using the new mobile authenticator version of SteamGuard.

**Comment by Fyren** [comment]
In case it's of any use, I'll reiterate part of my comment from #97 here:

WIth my account set to use the app for 2FA, it looks like right now the minimum change required to authenticate is to send the auth code as twofactorcode.  My lazy minimal edit was to add ```STEAM_HTTP_PAIR("twofactorcode", authcode)``` to ```steam_api_req_auth```.  Sending it along with ```emailauth``` seems to work fine.  Perhaps also helpful is checking for ```requires_twofactor``` in ```steam_api_cb_auth``` so you don't get the empty error message and instead show the same thing you do for e-mail auth.

But I have no idea about Steam's APIs so I have no clue if this is the _right_ way to do anything.

**Comment by jgeboski** [comment]
Resolved as of 3a96383.
