### ISSUE TITLE
Send raw IRC message to user

### ISSUE THREAD

**Issue by edwardmuel** [jgeboski/bitlbee-steam#78]
Is there a proper way to send a raw IRC message from bitlbee-steam to the connected user?

I am making use of how [ZNC supports sending sent private messages to all attached clients](http://wiki.znc.in/Privmsg) to implement support of displaying my messages sent from other non-bitlbee Steam connections.

I have done the following:
* added `STEAM_USER_MSG_TYPE_MY_SAYTEXT` and `STEAM_USER_MSG_TYPE_MY_EMOTE` to `SteamUserMsgType` in steam-user.h
* added `{STEAM_USER_MSG_TYPE_MY_SAYTEXT, "my_saytext"}, {STEAM_USER_MSG_TYPE_MY_EMOTE, "my_emote"},` to both `steam_user_msg_type_str()` and `steam_user_msg_type_from_str()` in steam-user.c
* added cases for `STEAM_USER_MSG_TYPE_MY_SAYTEXT` and `STEAM_USER_MSG_TYPE_MY_EMOTE` to the first set of cases in both switches in steam-api.c
* added the following code to `steam_user_msg()` in steam.c:
```C
static void steam_user_msg(SteamData *sata, SteamUserMsg *msg, gint64 time)
{
//beginning of steam_user_msg() untouched
    switch (msg->type) {
    case STEAM_USER_MSG_TYPE_MY_EMOTE:
    case STEAM_USER_MSG_TYPE_MY_SAYTEXT: //same as TYPE_EMOTE and TYPE_SAYTEXT with OPT_TYPING removed and imcb_buddy_msg() replaced
        bu = imcb_buddy_by_handle(sata->ic, sid);
        if (msg->type == STEAM_USER_MSG_TYPE_MY_EMOTE)
            str = g_strconcat("/me ", msg->text, NULL);
        else
            str = g_strdup(msg->text);
            
        //irc_send_msg_raw(irc_user_t *iu, const char *type, const char *dst, const char *msg)
        //void irc_send_msg_raw(irc_user_t *iu, const char *type, const char *dst, const char *msg) { irc_write(iu->irc, ":%s!%s@%s %s %s :%s", iu->nick, iu->user, iu->host, type, dst, msg && *msg ? msg : " "); }
        
        //irc_write(irc_t *irc, char *format, ...)
        //irc_write_all(int now, char *format, ...)
        
        //sata->ic->bee->user | ->nick | ->fullname (tried these but sata->ic->bee->user->nick and/or sata->ic->bee->user->fullname causes a segfault)
        
        irc_write_all(TRUE, ":%s!%s@localhost PRIVMSG %s :%s", "[username here]", "[realname here]", bu->nick, str);
        g_free(str);
        return;
//rest of steam_user_msg() untouched
}
```

This works, but it is not an ideal solution because the username, realname, and hostname are hardcoded. I don't think that `irc_write_all()` is a proper solution (it may be sending the message to all connected clients, but I am unsure because I'm the only user and I only use one connection).

Is there a way to access `irc_user_t` from bitlbee-steam for `irc_send_msg_raw()` or `irc_write()`?
I couldn't find any way to access it. (`irc_user_t` contains everything needed for using `irc_send_msg_raw()` or `irc_write()`: `irc_t`, username, realname, and hostname)

Every message I send causes a blank line to be sent to the bitlbee server tab (I connect to my bitlbee using ZNC). I don't know if this is how `irc_write_all()` functions or if I'm doing something wrong.
This does not show up in the IRC client's raw log, but if I enable the ZNC raw module, the following happens when I send a message from another Steam connection:
>[12:28] <*raw> IRC -> []
>[12:28] <*raw> IRC -> [:username!realname@localhost PRIVMSG steam-user :message]

**Comment by chauffer** [comment]
Any chance you could push the forked code on GitHub? I'm interested in this feature.

**Comment by edwardmuel** [comment]
I have pushed the forked code to https://github.com/edwardmuel/bitlbee-steam

Keep in mind that the way I'm doing things could have issues other than the two I have encountered so far: blank lines being printed to the server tab and user data being hardcoded. (If I had to guess, `irc_write_all()` probably isn't meant to be used by plugins)
Some IRC clients require an extra script to handle it properly, or they may not support it at all (see the ZNC URL in the issue).

Without any luck, I spent a while trying to find access to `irc_user_t`, which would (probably) allow a more appropriate solution.

**Comment by jgeboski** [comment]
I have talked with @dequis about supporting this in mainline bitlbee.  I would rather this not be plugin specific as many plugins can make use of such a feature.  Moreover, there is just a ton of hackery involved in making this function properly within a protocol plugin.  That said, for now I have no intentions of supporting this in the plugin until the functionality is in mainline bitlbee.  When I get some free time, I will probably create patch(es) for such functionality unless someone else beats me to the punch.

**Comment by dequis** [comment]
This is about self messages, right? The ticket description is so focused on its hacky implementation that i could barely tell.

**Comment by edwardmuel** [comment]
Yes, self messages. Sorry about that.

**Comment by jgeboski** [comment]
Closing this until bitlbee implements support for self messages.
