### ISSUE TITLE
Misleading instructions

### ISSUE THREAD

**Issue by kortemik** [jgeboski/bitlbee-steam#79]
```
Usage:
  Getting started:
    > account add steam <username> <password>
    > account <acc> on

  Authenticating with SteamGuard:
    > account <acc> set authcode <code>

  Captcha interaction may be required:
    > account <acc> set captcha <text>

  Output game play statues to the account channel(s):
    > account <acc> set game_status true

  Disable game play statuses (default: %):
    > account <acc> set show_playing false
``` 

Should be rather following. I spend around 30minutes figuring it out and I don't think I am that newbie when it comes to bitlbee or steam.
``` 
Getting started

- Add account:
> account add steam ExampleUser
> /OPER <enter your password for ExampleUser>

- Enable it to get captcha
> account steam on

- Download the captcha. URL displayed on the output, bellow "Login error: Please verify your humanity by re-entering the characters below." after enabling the account
> curl  https://steamcommunity.com/public/captcha.php?gid=<###> -o captcha.png
View and verify it.

- Enter the captcha
>  account steam set captcha ABC%EF

- Check email for SteamGuard authcode and enter it
> account steam set authcode A1B2C
```

**Comment by dequis** [comment]
You should probably add code blocksto your description so it's readable  (``` before and after) 

Plaintext version of the ticket description: http://dump.dequis.org/sVScP.txt

I don't really see the difference, other than the first step, where you provide the password with /oper instead of including it in the "account add" command.

The captcha... you're usually expected to open the link with the usual methods (such as mouse clicking or a url selector tool) and open it in a web browser. Curl is fine too, I just think that should be up to the tastes of the user.

I'm definitely not getting something here.

**Comment by kortemik** [comment]
Oh that's true, added those blocks.

The original guide had captcha and code in reverse order, that was really confusing. I had to dig into the resolved issues to see how to do it.

Opening the link from the _same_ IP-address as bitlbee is running on is quite hard for most of the users, i think, because most bitlbees run on shell hardware which is run on different machine than their end user web-browser. this is due to the nature of bitlbee.

Also using oper for the password input is really adviced as steam password is like access to second wallet for some of us.

I hope this clarifies it a bit.

**Comment by jgeboski** [comment]
Does the captcha actually require being opened from the same address now?

**Comment by kortemik** [comment]
> Does the captcha actually require being opened from the same address now?

No idea, but i read from previous issues that it might affect. Feel free to skip that one.

**Comment by jgeboski** [comment]
I am closing this.  This is mainly just nitpicks.  If something in here is actually required, please send a pull request.
