### ISSUE TITLE
Use newer chat history APIs

### ISSUE THREAD

**Issue by jgeboski** [jgeboski/bitlbee-steam#87]
With the recent release of the updated mobile application, Valve has enabled chat history.  This now uses new OAuth based APIs for retrieving the history, timestamps, and unread counts.  Using these newer APIs will allow the plugin to no longer send repeated requests to `steamcommunity.com/chat`, which has always been quite hackey.  Negating the calls to the Steam Community should result in a lower amount of HTTP requests as well.

**Comment by jgeboski** [comment]
This will also likely resolve #80.

**Comment by rathsky** [comment]
Looks like the new code currently polls incoming messages even after they've already been displayed.

Last time, about 50 mins after login, I got all messages a contact had written to me since that login and the previous logout redisplayed in one batch (as offline messages, ie. wtih timestamps).

**Comment by jgeboski** [comment]
This has been resolved as of aaf2cbc.
