### ISSUE TITLE
Unexpected when seeking value on friend request accepted 

### ISSUE THREAD

**Issue by chauffer** [jgeboski/bitlbee-steam#91]
![](https://c.meo.ws/1439660913_en1xwB.png)

Steps to reproduce:
* Accept a friend request

Behaviour encountered:
* Steam signs off, reconnects after five seconds
* _edit_: The request is not accepted

**Comment by jgeboski** [comment]
Steam is breaking all the things! :(

**Comment by chauffer** [comment]
Also, friends are not actually added.

**Comment by jgeboski** [comment]
This should be fixed as of 485ee3d.  Could you confirm?

**Comment by jgeboski** [comment]
You will likely need to re-authenticate in order for this to work.

```
> account <acc> off
> account <acc> set -del token
> account <acc> on
```

**Comment by jgeboski** [comment]
Since this works for me, I am going to assume it works for you.  I am trying to push a bug fix release out the door.

**Comment by chauffer** [comment]
It does work! :+1:
