### ISSUE TITLE
freebsd with bitlbee  3.4.1

### ISSUE THREAD

**Issue by devcline** [jgeboski/bitlbee-steam#95]
while ./autogen.sh i have this
Bitlbee is installed from ports
What can i doo?
thanks

configure: error: Package requirements (bitlbee  >= 3.4) were not met:

Package bitlbee was not found in the pkg-config search path.
Perhaps you should add the directory containing `bitlbee.pc'
to the PKG_CONFIG_PATH environment variable
Package 'bitlbee', required by 'world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables BITLBEE_CFLAGS
and BITLBEE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by dequis** [comment]
@rbgarga the bitlbee freebsd ports package doesn't seem to be doing install-dev

**Comment by rbgarga** [comment]
Fixed in 3.4.1_3. Thanks!

**Comment by dequis** [comment]
Nice! Thank you!
