### ISSUE TITLE
Steam Guard: Login error: (no error)

### ISSUE THREAD

**Issue by Tmplt** [jgeboski/bitlbee-steam#97]
When I create a steam bitlbee account and set `authcode` to what Steam Guard gives me, bitlbee tries to log in with the following error:

```
│22:20 @tmplt ╡ account steam set authcode 6RRM3
│22:20  @root ╡ steam - Logging in: Connecting
│22:20      ↪ ╡ steam - Logging in: Requesting authentication key
│22:20      ↪ ╡ authcode = `6RRM3'
│22:20      ↪ ╡ steam - Logging in: Requesting authentication token
│22:20      ↪ ╡ steam - Login error:
│22:20      ↪ ╡ steam - Logging in: Signing off..
```

**Comment by jgeboski** [comment]
Are you using the Steam Mobile Two-Factor authentication? Does it ever throw an error? Have you tried to turn the account on after it signs you off?

**Comment by Tmplt** [comment]
Yes, I believe it's the two-factor authentication. I've tried to manually turn the account on, but it also does that when I enter a new `authcode`. Anyway, it doesn't even throw an error.

**Comment by Fyren** [comment]
Oops, it does seem to be a dupe.

For 2FA, it seems like if you send twofactorcode rather than emailauth.  If you send both, it still works.  I'm able to log in with my lazy local edit and 2FA with the Steam app rather than e-mail.

**Comment by Tmplt** [comment]
I never realized I could do that, and indeed I can log in now. Thanks!

**Comment by jgeboski** [comment]
See #75 for 2FA support. A workaround has been proposed, so I am closing this issue.
